/home/galmagro/anaconda3/envs/openea/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/galmagro/anaconda3/envs/openea/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/galmagro/anaconda3/envs/openea/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/galmagro/anaconda3/envs/openea/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/galmagro/anaconda3/envs/openea/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/galmagro/anaconda3/envs/openea/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:532: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "main_from_args.py", line 5, in <module>
    from openea.modules.args.args_hander import check_args, load_args
  File "/home/galmagro/OpenEA/src/openea/__init__.py", line 19, in <module>
    from openea import models
  File "/home/galmagro/OpenEA/src/openea/models/__init__.py", line 1, in <module>
    from openea.models import trans
  File "/home/galmagro/OpenEA/src/openea/models/trans/__init__.py", line 1, in <module>
    from openea.models.trans.transe import TransE
  File "/home/galmagro/OpenEA/src/openea/models/trans/transe.py", line 4, in <module>
    from openea.models.basic_model import BasicModel
  File "/home/galmagro/OpenEA/src/openea/models/basic_model.py", line 13, in <module>
    from openea.modules.finding.evaluation import valid, test, early_stop
  File "/home/galmagro/OpenEA/src/openea/modules/finding/evaluation.py", line 3, in <module>
    from openea.modules.finding.alignment import greedy_alignment
  File "/home/galmagro/OpenEA/src/openea/modules/finding/alignment.py", line 9, in <module>
    from openea.modules.finding.similarity import sim
  File "/home/galmagro/OpenEA/src/openea/modules/finding/similarity.py", line 4, in <module>
    from scipy.spatial.distance import cdist
  File "/home/galmagro/anaconda3/envs/openea/lib/python3.6/site-packages/scipy/spatial/__init__.py", line 102, in <module>
    from ._geometric_slerp import geometric_slerp
  File "/home/galmagro/anaconda3/envs/openea/lib/python3.6/site-packages/scipy/spatial/_geometric_slerp.py", line 8, in <module>
    from scipy.spatial.distance import euclidean
  File "/home/galmagro/anaconda3/envs/openea/lib/python3.6/site-packages/scipy/spatial/distance.py", line 118, in <module>
    from . import _distance_wrap
ImportError: /home/galmagro/anaconda3/envs/openea/lib/python3.6/site-packages/scipy/spatial/_distance_wrap.cpython-36m-x86_64-linux-gnu.so: invalid ELF header
